# Makefile for the Twine threading library
# $ make all     # Build library + test program
# $ make lib     # Build library (thread.o)

OFILES = thread.o twine.o
CC = gcc
OUTFILE = twine
FLAGS = -D__MAKECONTEXT_V2_SOURCE -Wall
SHELL = /bin/sh

all:   $(OFILES)
	$(CC) $(FLAGS)  $(OFILES) -o $(OUTFILE)

lib:   
	$(CC) $(FLAGS) -c thread.c -o thread.o

clean:   
	-rm -rf $(OFILES)
	-rm -rf $(OUTFILE)

# Generated by Ruby2Make
