
OFILES = thread.o stringtest.o
CC = gcc
OUTFILE = thread
FLAGS = -D__MAKECONTEXT_V2_SOURCE -Wall
SHELL = /bin/sh

all:   $(OFILES)
	$(CC) $(FLAGS)  $(OFILES) -o $(OUTFILE)

lib:   
	$(CC) $(FLAGS) -c thread.c -o thread.o

clean:   
	-rm -rf $(OFILES)
	-rm -rf $(OUTFILE)

# Generated by Ruby2Make

