# Makefile for the Twine threading library
# $ make all     # Build library + test programs
# $ make lib     # Build library (thread.o)

CC = gcc
FLAGS = -D__MAKECONTEXT_V2_SOURCE -Wall
SHELL = /bin/sh

all:   mutex_test thread_test

mutex_test:   thread.o mutex_test.o
	$(CC) $(FLAGS)  thread.o mutex_test.o -o mutex_test

thread_test:   thread.o thread_test.o
	$(CC) $(FLAGS)  thread.o thread_test.o -o thread_test

lib:   
	$(CC) $(FLAGS) -c thread.c -o thread.o

clean:   
	-rm -rf thread.o
	-rm -rf thread_test.o
	-rm -rf mutex_test.o
	-rm -rf thread_test
	-rm -rf mutex_test

# Generated by Ruby2Make
